
env:
  global:
    - secure: TnTGMjGO4i2SgcDtqOKADL1/0iHI3SomEDqn2/9+5vepTmOxPTkEYSwgtcvw0HLBnB5rHFvpi5FcUZCXEbe9OuaR2re2nyQFOw5Cz03CB9L4iNwtlE1OUUhCPsKI7skrkhTjDxJ/eXdaKOY2ER6Wt55BzKaQysRSkf6ApJKbFjE=

language: perl

perl:
  - "5.16"

services:
  - rabbitmq

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y aspell

install:
  - cpanm --quiet --notest AnyEvent
  - cpanm --quiet --notest Devel::GlobalDestruction
  - cpanm --quiet --notest Module::Install::AuthorTests
  - cpanm --quiet --notest Net::AMQP
  - cpanm --quiet --notest Readonly
  - cpanm --quiet --notest Test::Perl::Critic
  - cpanm --quiet --notest Test::Spelling

before_script:
  - export GIT_DESC=`git describe --always | tr -d '\012'`

after_script:
  - Completed AnyEvent-RabbitMQ-${GIT_DESC}

before_deploy:
  - echo Deploying AnyEvent-RabbitMQ-${GIT_DESC}.tar.gz

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file: AnyEvent-RabbitMQ-${GIT_DESC}.tar.gz
  skip_cleanup: true
  on:
    tags: false
    all_branches: true

after_deploy:
  - echo Deployed AnyEvent-RabbitMQ-${GIT_DESC}.tar.gz
