language: perl

perl:
  - "5.16"

services:
  -rabbitmq

install:
  - cpanm --notest Module::Install::AuthorTests
  - cpanm --notest Net::AMQP
  - cpanm --notest AnyEvent
  - cpanm --notest Devel::GlobalDestruction
