on:
  push:
    branches:
    - master
    tags:
    - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        perl: [ '5.30', '5.28', '5.10' ]
      max-parallel: 2
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1.3.1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm --quiet --notest Module::Install Module::Install::AuthorTests Module::Install::AuthorRequires Test::Pod Test::Spelling Test::Perl::Critic
      - run: perl Makefile.PL
      - run: cpanm --quiet --notest --installdeps .
      - run: make
      - run: make test
      - run: prove -Iblib/lib -r xt/
